# Generated by Django 5.1.4 on 2025-01-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameoption',
            name='authorId',
        ),
        migrations.RemoveField(
            model_name='gameoption',
            name='authors_option',
        ),
        migrations.AddField(
            model_name='gameoption',
            name='authorCharfield',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='gameoption',
            name='option1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='gameoption',
            name='option2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='gameoption',
            name='option3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='gameoption',
            name='option4',
            field=models.CharField(default='', max_length=200),
        ),
    ]
