# Generated by Django 5.1.4 on 2025-01-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_gameoption_authorid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameoption',
            old_name='authorCharfield',
            new_name='author',
        ),
    ]
