# Generated by Django 5.1.4 on 2025-01-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_authorcharfield_gameoption_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameoption',
            name='option4',
        ),
    ]
