# Generated by Django 5.1.4 on 2025-01-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_gameoption_option4'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameoption',
            name='option4',
            field=models.CharField(default='', max_length=200),
        ),
    ]
