
import analyze_market
import json
import os
import datetime

def generate_html(results):
    json_data = json.dumps(results)
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stonks Market Report</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f4f4f9; color: #333; margin: 0; padding: 20px; }}
        h1 {{ text-align: center; color: #2c3e50; margin-bottom: 5px; }}
        .header {{ text-align: center; margin-bottom: 25px; color: #7f8c8d; font-size: 0.9em; }}
        
        /* Scrollable Tabs */
        .tabs-container {{ width: 100%; overflow-x: auto; background: white; padding: 10px 0; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); margin-bottom: 20px; white-space: nowrap; -webkit-overflow-scrolling: touch; }}
        .tabs {{ display: inline-flex; padding: 0 10px; }}
        .tab-btn {{ background: transparent; border: none; padding: 10px 15px; cursor: pointer; transition: 0.2s; margin: 0 2px; border-radius: 20px; font-size: 0.95em; color: #555; }}
        .tab-btn.active {{ background: #3498db; color: white; font-weight: bold; }}
        .tab-btn:hover:not(.active) {{ background: #e9ecef; }}

        /* Content */
        .tab-content {{ display: none; animation: fadeIn 0.4s; }}
        .tab-content.active {{ display: block; }}
        
        @keyframes fadeIn {{ from {{ opacity: 0; transform: translateY(5px); }} to {{ opacity: 1; transform: translateY(0); }} }}

        /* Table */
        .table-container {{ overflow-x: auto; background: white; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); padding: 20px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
        th, td {{ padding: 12px 15px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #f8f9fa; font-weight: 600; cursor: pointer; user-select: none; color: #555; }}
        th:hover {{ background-color: #e2e6ea; }}
        tr:hover {{ background-color: #f8f9fa; }}
        
        .positive {{ color: #27ae60; font-weight: bold; }}
        .negative {{ color: #c0392b; font-weight: bold; }}
        
        /* Stats cards */
        .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 20px; }}
        .card {{ background: white; padding: 15px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); text-align: center; border-top: 3px solid transparent; }}
        .card h3 {{ margin: 0 0 5px; color: #95a5a6; font-size: 0.8em; text-transform: uppercase; letter-spacing: 1px; }}
        .card p {{ margin: 0; font-size: 1.1em; font-weight: bold; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }}
        
        .card-best {{ border-top-color: #27ae60; }}
        .card-worst {{ border-top-color: #c0392b; }}
        .card-total {{ border-top-color: #3498db; }}

    </style>
</head>
<body>

    <h1>🚀 Stonks Market Report</h1>
    <div class="header">Generated on {timestamp}</div>

    <div class="tabs-container">
        <div class="tabs" id="tabs">
            <!-- Tabs generated by JS -->
        </div>
    </div>

    <div id="content">
        <!-- Content generated by JS -->
    </div>

    <script>
        const data = {json_data};

        function init() {{
            const tabsContainer = document.getElementById('tabs');
            const contentContainer = document.getElementById('content');
            
            let first = true;

            for (const key in data) {{
                const item = data[key];
                const title = item.title;
                const rows = item.data;

                // Create Tab
                const btn = document.createElement('button');
                btn.className = `tab-btn ${{first ? 'active' : ''}}`;
                btn.innerText = title;
                btn.onclick = () => switchTab(key);
                tabsContainer.appendChild(btn);

                // Create Content Div
                const div = document.createElement('div');
                div.id = `content-${{key}}`;
                div.className = `tab-content ${{first ? 'active' : ''}}`;
                
                // Calculate stats
                const gainers = rows.filter(r => r.change > 0).length;
                const losers = rows.filter(r => r.change < 0).length;
                
                // Determine Best and Worst
                let best = {{name: 'N/A', change_str: '-'}};
                let worst = {{name: 'N/A', change_str: '-'}};

                if (rows.length > 0) {{
                     best = rows[0];
                     worst = rows[rows.length - 1];
                }}

                let html = `
                    <div class="stats">
                        <div class="card card-total"><h3>Analyzed</h3><p>${{rows.length}}</p></div>
                        <div class="card card-total"><h3>Gainers</h3><p style="color:#27ae60">${{gainers}}</p></div>
                        <div class="card card-total"><h3>Losers</h3><p style="color:#c0392b">${{losers}}</p></div>
                        <div class="card card-best"><h3>Best Performance</h3><p class="positive" title="${{best.name}}">${{best.ticker}} (${{best.change_str}})</p></div>
                        <div class="card card-worst"><h3>Worst Performance</h3><p class="negative" title="${{worst.name}}">${{worst.ticker}} (${{worst.change_str}})</p></div>
                    </div>
                    <div class="table-container">
                        <table id="table-${{key}}" data-order="asc">
                            <thead>
                                <tr>
                                    <th onclick="sortTable('${{key}}', 0)">Ticker ⬍</th>
                                    <th onclick="sortTable('${{key}}', 1)">Company ⬍</th>
                                    <th onclick="sortTable('${{key}}', 2)">Price ⬍</th>
                                    <th onclick="sortTable('${{key}}', 3)">Change % ⬍</th>
                                </tr>
                            </thead>
                            <tbody>
                `;

                rows.forEach(r => {{
                    const colorClass = r.change >= 0 ? 'positive' : 'negative';
                    html += `
                        <tr>
                            <td>${{r.ticker}}</td>
                            <td>${{r.name}}</td>
                            <td>${{r.price_str}}</td>
                            <td class="${{colorClass}}" data-val="${{r.change}}">${{r.change_str}}</td>
                        </tr>
                    `;
                }});

                html += `</tbody></table></div>`;
                div.innerHTML = html;
                contentContainer.appendChild(div);

                first = false;
            }}
        }}

        function switchTab(key) {{
            // Buttons
            document.querySelectorAll('.tab-btn').forEach(b => {{
                if (b.innerText === data[key].title) b.classList.add('active');
                else b.classList.remove('active');
            }});
            
            // Content
            document.querySelectorAll('.tab-content').forEach(d => d.classList.remove('active'));
            document.getElementById(`content-${{key}}`).classList.add('active');
        }}

        function sortTable(key, colIndex) {{
            const table = document.getElementById(`table-${{key}}`);
            const tbody = table.querySelector('tbody');
            const rows = Array.from(tbody.querySelectorAll('tr'));
            
            const currentOrder = table.getAttribute('data-order') || 'asc';
            const newOrder = currentOrder === 'asc' ? 'desc' : 'asc';
            table.setAttribute('data-order', newOrder);

            rows.sort((a, b) => {{
                const cellA = a.children[colIndex].innerText;
                const cellB = b.children[colIndex].innerText;
                
                // Sort by change % (col 3)
                if (colIndex === 3) {{
                   const valA = parseFloat(a.children[colIndex].getAttribute('data-val'));
                   const valB = parseFloat(b.children[colIndex].getAttribute('data-val'));
                   return newOrder === 'asc' ? valA - valB : valB - valA;
                }}
                
                // Sort by price (col 2) - extract number
                if (colIndex === 2) {{
                   const valA = parseFloat(cellA.replace(/,/g, ''));
                   const valB = parseFloat(cellB.replace(/,/g, ''));
                   return newOrder === 'asc' ? valA - valB : valB - valA;
                }}

                return newOrder === 'asc' ? cellA.localeCompare(cellB) : cellB.localeCompare(cellA);
            }});

            rows.forEach(r => tbody.appendChild(r));
        }}

        init();
    </script>
</body>
</html>
    """
    
    with open("market_report.html", "w") as f:
        f.write(html_content)
    
    print("Report generated: market_report.html")

def main():
    print("Gathering data and generating interactive report...")
    data = analyze_market.get_market_trends()
    generate_html(data)
    print("Done! Open 'market_report.html' in your browser.")
    
    # Summary of prices as well?
    print("\\nTop Movers Summary:")
    for key, val in data.items():
        if val['data']:
             top = val['data'][0]
             worst = val['data'][-1]
             print(f"{val['title']}:")
             print(f"  Best:  {top['ticker']} ({top['change_str']}) [${top['price_str']}]")
             print(f"  Worst: {worst['ticker']} ({worst['change_str']}) [${worst['price_str']}]")

if __name__ == "__main__":
    main()
